//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quimipac_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuRol
    {
        public int Id_MenuRol { get; set; }
        public Nullable<int> Id_Rol { get; set; }
        public Nullable<int> Id_Menu { get; set; }
        public string Estado { get; set; }
    }
}
