//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quimipac_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_Equipo_Referencia
    {
        public int Id_Equipo { get; set; }
        public string Id_Proveedor { get; set; }
        public Nullable<int> Id_Persona_asignada { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Numero_Serie { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Horas_Usadas { get; set; }
    }
}
