//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quimipac_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_GrupoTrabajoEquipo
    {
        public int Id_GrupoTrabajoEquipo { get; set; }
        public Nullable<int> Id_GrupoTrabajo { get; set; }
        public Nullable<int> Id_Equipo { get; set; }
        public string Estado { get; set; }
    }
}
