//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quimipac_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_Materiales_Solicitud
    {
        public int Id_Material_Solicitud { get; set; }
        public Nullable<int> Id_Solicitud { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string Id_Item { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Estado { get; set; }
    }
}
