//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quimipac_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_OrdenTrabajo_Egreso
    {
        public int Id_OrdenTrabajo_Egreso { get; set; }
        public Nullable<int> Id_Orden_Trabajo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Moneda { get; set; }
        public string Unidad { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Id_Item { get; set; }
        public string EstadoAct { get; set; }
        public string Id_Usuario { get; set; }
        public string Id_Usuario_Modifica { get; set; }
        public Nullable<System.DateTime> Fecha_Modifica { get; set; }
    
        public virtual MT_OrdenTrabajo MT_OrdenTrabajo { get; set; }
    }
}
