//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quimipac_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_OrdenTrabajo_Novedad
    {
        public int Id_OrdenTrabajo_Novedad { get; set; }
        public Nullable<int> Id_Orden_Trabajo { get; set; }
        public string Id_Usuario { get; set; }
        public string Tipo_Novedad { get; set; }
        public string Novedad { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Id_Dirigido_a1 { get; set; }
        public string Id_Dirigido_a2 { get; set; }
        public string Id_Dirigido_a3 { get; set; }
        public string Id_Dirigido_a4 { get; set; }
    
        public virtual MT_OrdenTrabajo MT_OrdenTrabajo { get; set; }
    }
}
