//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quimipac_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_OrdenTrabajo_Actividad
    {
        public int Id_OrdenTrabajo_Actividad { get; set; }
        public Nullable<int> Id_Orden_Trabajo { get; set; }
        public Nullable<int> Id_Actividad { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<System.DateTime> Fecha_Ini { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
        public string Comentario { get; set; }
        public string EstadoAct { get; set; }
        public string Id_Usuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Id_Usuario_Modifica { get; set; }
        public Nullable<System.DateTime> Fecha_Modifica { get; set; }
        public string Responsable { get; set; }
        public string Nombre_Actividad { get; set; }
    
        public virtual MT_OrdenTrabajo MT_OrdenTrabajo { get; set; }
    }
}
