//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quimipac_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_Proyecto_Actividad_Valor
    {
        public int Id_Proyecto_Actividad_Valor { get; set; }
        public Nullable<int> Id_Proyecto_Actividad { get; set; }
        public string Id_Usuario { get; set; }
        public Nullable<int> Tipo_Valor { get; set; }
        public string Id_Item { get; set; }
        public string Moneda { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Unidad { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> IVA { get; set; }
    
        public virtual MT_Proyecto_Actividad MT_Proyecto_Actividad { get; set; }
    }
}
