//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quimipac_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_Proyecto_Actividad_Anexo
    {
        public int Id_Proyecto_Actividad_Anexo { get; set; }
        public Nullable<int> Id_Proyecto_Actividad { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Descripcion { get; set; }
        public string Enlace { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual MT_Proyecto_Actividad MT_Proyecto_Actividad { get; set; }
    }
}
