//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quimipac_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_Permiso
    {
        public int Id_Permiso { get; set; }
        public string Id_Usuario { get; set; }
        public string Id_Cliente { get; set; }
        public Nullable<int> Id_Contrato { get; set; }
        public Nullable<int> Id_Proyecto { get; set; }
        public Nullable<int> Id_Tipo_Trabajo { get; set; }
        public string Id_Linea { get; set; }
        public string Consultar { get; set; }
        public string Modificar { get; set; }
        public string Crear { get; set; }
        public string Eliminar { get; set; }
        public string Aprobar { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public string Estado { get; set; }
        public string Id_Empresa { get; set; }
        public Nullable<int> Id_Prospecto { get; set; }
    }
}
