//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quimipac_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_Presupuesto_Detalle
    {
        public int Id_Presupuesto_detalle { get; set; }
        public Nullable<int> Id_Presupuesto { get; set; }
        public string Id_Item { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string unidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> IVA { get; set; }
    }
}
