//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quimipac_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_Presupuesto
    {
        public int Id_Presupuesto { get; set; }
        public string Id_Empresa { get; set; }
        public string Id_Sucursal { get; set; }
        public string Id_Cliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Id_Usuario { get; set; }
        public string Comentario { get; set; }
        public Nullable<decimal> Porcentaje_indirectos { get; set; }
        public Nullable<decimal> Monto_Certificacion { get; set; }
        public Nullable<decimal> Iva_Certificacion { get; set; }
        public string Validez { get; set; }
        public string Moneda { get; set; }
    }
}
