//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quimipac_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_Servicio
    {
        public int Id_Servicio { get; set; }
        public string Id_Empresa { get; set; }
        public Nullable<int> Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
    }
}
