//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quimipac_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_TipoTrabajo
    {
        public int Id_TipoTrabajo { get; set; }
        public string Id_Cliente { get; set; }
        public string Id_Usuario { get; set; }
        public string Codigo { get; set; }
        public string Linea { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public string Control_Item { get; set; }
        public string Control_Equipo { get; set; }
        public string Control_Integrante { get; set; }
        public string Control_Anexo { get; set; }
        public string Control_Medida { get; set; }
        public string Control_Costo { get; set; }
        public Nullable<int> Id_Servicio { get; set; }
        public Nullable<int> Id_Padre { get; set; }
        public string Control_Raiz { get; set; }
        public Nullable<int> Proceso { get; set; }
        public Nullable<int> Alerta { get; set; }
        public Nullable<int> Caida { get; set; }
        public Nullable<int> Clasificacion { get; set; }
    }
}
