//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quimipac_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_TipoTrabajo_Item
    {
        public int Id_TipoTrabajo_Item { get; set; }
        public int Id_Tipo_Trabajo { get; set; }
        public int Id_Item { get; set; }
        public Nullable<double> Unidad { get; set; }
    }
}
